### ISSUE TITLE
r console not working

### ISSUE THREAD

**Issue by alambarr** [StructuredDataLLC/Basic-Excel-R-Toolkit#2]
I downloaded the latest version. Excel 2010, Windows 7, 32 bit. Typing commands into the console does not work, but clicking on install packages does.
![image](https://cloud.githubusercontent.com/assets/10732996/5929717/67944452-a63b-11e4-80d1-0bd7821cba31.png)

**Comment by duncanwerner** [comment]
I'll spin up a vm to test that setup.  Is it 32-bit Windows also?

Let me clarify a couple of things: (1) were there any errors at the top of the console when you started it?  (2) do functions work in the spreadsheet?  And (3) for no reason at all, did you try rebooting?

**Comment by alambarr** [comment]
Yup windows 32 bit. 1. No errors. 2 Functions within Excel work. 3. Didn't  try :( I did uninstall, re-install BERT but that didn't fix it. Will attempt when I get back to the office in the morning. Thanks for the super fast reply!

**Comment by duncanwerner** [comment]
I wasn't able to reproduce this on a clean VM, so I'm not sure what's happening.  If you're interested we could instrument a build and run through it; but only if you want to spend the time.

**Comment by alambarr** [comment]
That would be helpful. Let me know when you can do it.

**Comment by duncanwerner** [comment]
As I was working through instrumenting this I think I figured out what was causing it.  I am reasonably sure that the new release (0.31) will resolve it, but I don't really know unless you can test it.  Let me know if you get a chance.

**Comment by wck01** [comment]
I install the new release 0.4 but has the same issue. I'm using Windows 64 bit and Excel 2010 64 bit. There is nothing happened whatever I type in console. Could you help? Thanks in advance.

**Comment by wck01** [comment]
Just updated to release 0.41 but still not working in Excel 2010.

**Comment by duncanwerner** [comment]
Closed with fix for issue #4
